services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=mydb
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - app_network

  migrate:
    image: migrate/migrate
    entrypoint: ["migrate", "-path", "/migrations", "-database", "postgres://postgres:password@db:5432/mydb?sslmode=disable", "up"]
    volumes:
      - ./migrations:/migrations
    depends_on:
      - db

volumes:
  db_data:

networks:
  app_network:
